### ISSUE TITLE
[Bug/improvement] Issue with saliency maps in loop

### ISSUE THREAD

**Issue by ricvolpe** [jalammar/ecco#16]
Hey,

In Colab, I am trying to generate saliency maps in a loop to study variations of similar inputs, but when you print the maps generate in a loop, they are stuck next to each other which makes the visualisation quite confusing.
See screenshot.

![Screen Shot 2020-12-29 at 20 13 34](https://user-images.githubusercontent.com/24500682/103308354-8e2b4800-4a12-11eb-872c-99da77a58966.png)

**Comment by jalammar** [comment]
Ah! Interesting. Didn't consider this before. I've added an issue in the javascript repo: https://github.com/jalammar/eccojs/issues/1
