### ISSUE TITLE
Support batched inference

### ISSUE THREAD

**Issue by jalammar** [jalammar/ecco#19]
Currently, `generate()` only works with a single input. Ecco should support batched inference.

I am currently working on this in https://github.com/jalammar/ecco/tree/batch-input-activations

This is tied to #18 and `__call__` should support batching on its launch. This has an effect on the `output.activations` tensor, and will bump its dimensions from 
`(layer, neuron, position)`
 to become:
`(batch, layer, neuron, position)`

**Comment by mehmetanbaki** [comment]
Great Job
