### ISSUE TITLE
Add Beam Search Support

### ISSUE THREAD

**Issue by Nempickaxe** [jalammar/ecco#25]
I'm not finding any way to do beam search using ecco, can you add the same in documentation?

**Comment by jalammar** [comment]
It's not possible to do beam search yet, unfortunately. I'll flag this issue to welcome contributions.

The required change would be in `generate()` and `_generate_token()` in [lm.py](https://github.com/jalammar/ecco/blob/main/src/ecco/lm.py). The functionality exists in the transformers file [generation_utils](https://github.com/huggingface/transformers/blob/b020a736c374460af1b34267283f957988350630/src/transformers/generation_utils.py) under the flags `is_beam_gen_mode` and `is_beam_sample_gen_mode`.
