### ISSUE TITLE
Support for T5-like Seq2SeqLM

### ISSUE THREAD

**Issue by chiragjn** [jalammar/ecco#39]
Hello, I was wondering if there are any plans for explicit encoder-decoder models like T5. Although T5 was not pre-trained with auto-regressive LM objective it is a pretty good candidate for ecco's `generate` method.
I tried running t5 as it was listed in `model-config.yaml` but soon ran into issues because the current implementation is very much suited to gpt like models.

I made some changes on a fork to get attribution working, but not sure if I did it correctly
https://colab.research.google.com/drive/1zahIWgOCySoQXQkAaEAORZ5DID11qpkH?usp=sharing
https://github.com/chiragjn/ecco/tree/t5_exp 

I would love to contribute to add support with some help, especially on the overall implementation design

**Comment by kara4141** [comment]
Is there any update regarding this? Thanks!

**Comment by jalammar** [comment]
Not yet, haven't had time to get into the details of how differently Ecco would need to work in the encoder-decoder setup as opposed to GPT and BERT. Happy to be educated if someone can walk me through it.

**Comment by chiragjn** [comment]
Oh nice! great find. It has been months since I have revisited my code. I'll push a change with this and re-run the sample notebook :)

**Comment by jalammar** [comment]
T5 is now supported
