### ISSUE TITLE
Add a `conda` install option for `ecco`

### ISSUE THREAD

**Issue by sugatoray** [jalammar/ecco#54]
A conda install option for `ecco` could be helpful for two reasons:

1. Easy installation with version management with conda.
2. For other libraries, which if depend on `ecco`, if you want them on conda-forge channel as well, `ecco` must be available on conda-forge.

:bulb: I have already have started work on this. PR: https://github.com/conda-forge/staged-recipes/pull/17388

Once, the PR gets merged, you will be able to install `ecco` as:

```sh
conda install -c conda-forge ecco
```

> I will send a PR to update your documentation, once the PR gets merged.

**Comment by sugatoray** [comment]
cc: @jalammar

**Comment by sugatoray** [comment]
:fire: The package was just added to conda-forge channel. Please give it 2-3 hours before it can be downloaded from conda-forge.

![image](https://user-images.githubusercontent.com/10201242/147792004-63660306-0332-46be-976c-2121cf6b90a3.png)

**Comment by sugatoray** [comment]
@jalammar I would like to add the following section to the `README.md` and `docs/index.md`. I would like to send a PR for the same. Please let me know if it is okay.

## Installation

You can install `ecco` either with `pip` or with `conda`.

**with pip**

```sh
pip install ecco
```

**with conda**

```sh
conda install -c conda-forge ecco
```

**Comment by jalammar** [comment]
Conda support is an excellent addition!

I faced the Windows failure and see some details on it in the thread. Can we add instructions to install pytorch first if on Windows. Perhaps a brief note like the following (below the conda command):
(On Windows: make sure you install [pytorch ](https://pytorch.org/)first)

Noob question: What's the process to update conda-forge with new releases? Does it collect them automatically from pypi? Or what needs to be done?

**Comment by sugatoray** [comment]
> Can we add instructions to install pytorch first if on Windows. Perhaps a brief note like the following (below the conda command):
(On Windows: make sure you install pytorch first)

This sounds reasonable to me. But need to test that it works given a pytorch installation exists on windows (in all likelihood, it would; but still).

> Noob question: What's the process to update conda-forge with new releases? Does it collect them automatically from pypi? Or what needs to be done?

Every conda-forge package is updated through a GitHub repository (`<package-name>-feedstock`) under conda-forge (organization) on GitHub. You will need to update the feedstock (`ecco-feedstock`) by sending a PR. I am the sole maintainer of it, so once I review it and we make any necessary changes to it, and merge it, that's it. The CI processes will do the rest, and in 2-3 hours the updated package will be available on conda-forge.

On a longer run, I would encourage you to become a maintainer of the conda-forge feedstock. Regular, PyPI updates are mostly picked up by conda-forge bots and they initiate a PR for updating the recipe. But, you could also initiate a PR right away when you push the new version to PyPI. This was you could more or less control how soon both PyPI and conda-forge can serve your latest versions.

Typically, maintaining the feedstock is fairly simple. Mostly in order to update the recipe, all you have to do is:

1. update the `version`
2. update the `sha256` (make sure you get this from PyPI)
3. if new version, set the build-number to `0`, otherwise if you are making modifications for in the recipe, for the same version, bump it up by `1`.
4. update the dependencies (if necessary) -- *for this part I would suggest you to consult me in the review process*

**Comment by sugatoray** [comment]
@jalammar I just posted about conda support for ecco on LinkedIn.

- [conda support for ecco on conda-ofrge channel](https://www.linkedin.com/posts/sugatoray_captum-conda-condaforge-activity-6882719779954679809-qbW1)

**Comment by jalammar** [comment]
Thank you for the awesome rundown, @sugatoray! I really appreciate it. Awesome post on LinkedIn as well!
