### ISSUE TITLE
GPT Generation error on GPU

### ISSUE THREAD

**Issue by jalammar** [jalammar/ecco#57]
Generating text with GPT2 on GPU throws the following error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

**Comment by JoaoLages** [comment]
Grabbing this issue in here: https://github.com/JoaoLages/ecco/tree/bugfix/issue_%2357
