### ISSUE TITLE
How to use ECCO to explain FineTuned T5 for Conditional Generation ?

### ISSUE THREAD

**Issue by tejas20** [jalammar/ecco#74]
I am trying to use ECCO to explain the output of FinedTuned T5 for Conditional Generation model which is fine tuned on table-to-text dataset. I am not able to load my model with the conditional generation.  Can you give me an example code of how to load local transformer models?

**Comment by tejas20** [comment]
Also example input from table is - <page_title> List of Governors of South Carolina </page_title> <section_title> Governors under the Constitution of 1868 </section_title> <table> <cell> 76 <col_header> # </col_header> <col_header> 74 </col_header> <col_header> 75 </col_header> </cell> <cell> Daniel Henry Chamberlain <col_header> Governor </col_header> <row_header> 76 </row_header> </cell> <cell> December 1, 1874 <col_header> Took Office </col_header> <row_header> 76 </row_header> </cell> </table> 
And Example output is - Daniel Henry Chamberlain was the 76th Governor of South Carolina from 1874.</s> <pad> <pad> <pad> <pad> <pad> 
Can ecco explain the input to output considering the <tags> in input text.

**Comment by jalammar** [comment]
You can load the local model as long as you provide its config info. See this [notebook](https://github.com/jalammar/ecco/blob/main/notebooks/Identifying%20model%20configuration.ipynb) for config info. You can probably use the same configurations of the original T5 (find these in the model-config file).

**Comment by tejas20** [comment]
Thank you, Jay. 
I have tried using the mentioned notebook. It loads the default config and default t5-base model fromhuggingface ( just pretrained without finetuning) and the output of generated text doesn't come out as expected as it contains the HTML <tags> like <pad/>. I want to pass my own finetuned t5 conditional generation model (stored locally) with its tokenizer to see the correct output and exactly how it is getting produced.
