### ISSUE TITLE
Support for Constrained Beam Search?

### ISSUE THREAD

**Issue by pablogranolabar** [jalammar/ecco#77]
Hola! Great project, thank you for making it available!

I am curious now that beam search is supported, is it possible to pass constraints to ecco using for example [PhrasalConstraints](https://huggingface.co/blog/constrained-beam-search), to constrain T5 model output for a sequence-to-sequence task prior to ecco evaluation?

Thanks in advance!

**Comment by JoaoLages** [comment]
It is!  If you look in [here](https://github.com/jalammar/ecco/blob/0ef61c51b76c48cd8c21c7807c20510565f307de/src/ecco/lm.py#L155), LM.generate accepts any extra argument as an argument to pass to model.generate
Just pass your logit constraints in there!
