### ISSUE TITLE
Problem with saliency()

### ISSUE THREAD

**Issue by Poul-Andersson** [jalammar/ecco#78]
I'm unable to get the saliency() commands in the notebook "Language_Models_and_Ecco_PyData.ipynb" to function. Given the command "output_3.saliency()", the error message is: "'OutputSeq' object has no attribute 'saliency'". Would greatly appreciate suggestions. Poul

**Comment by jalammar** [comment]
That's an outdated code block, sorry. See the https://github.com/jalammar/ecco/blob/main/notebooks/Ecco_Primary_Attributions.ipynb notebook for saliency (which is now renamed to primary_attributions)
